"""Local-only adapter for the user-supplied AI Village schema reference.

The column contract is known; this module does not authenticate dataset
versions, request gated access, download data, or execute source content.
Memory snapshots have no documented session foreign key. Provider responses
are preserved as JSON instead of being guessed into a common text format.
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import gzip
import hashlib
import json
from pathlib import Path
import re
from typing import Iterator
from uuid import UUID


TABLES = ("agents", "chat_messages", "agent_memories", "computer_use_sessions", "computer_use_turns")
SOURCE_CARD = "https://huggingface.co/datasets/aidigestorg/ai-village"
MATERIAL_UPDATE_WARNING_SECONDS = 1.0  # A conservative analysis warning, not a source guarantee of immutability.
_STAMP = re.compile(r"^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})?$")
LIMITATIONS = [
    "The adapter applies the user-supplied column schema; it does not authenticate an official dataset revision or export.",
    "Agent names are display labels. Identity joins use UUID columns rather than matching names or model strings.",
    "Agent names, model strings and state describe metadata at export time, not a verified historical model roster. Current-room/session pointers and last_seen_event_index are not historical joins or read receipts.",
    "Naive source timestamps are interpreted as UTC only under this AI Village schema contract.",
    "Memory rows contain snapshots and agent IDs, but no documented session or consolidation foreign key. No reset-survival or memory-injection link is inferred.",
    "The executed action field records a tool action, not proof that it succeeded. Model narration and intentions remain separate from execution and tool output.",
    "Provider-shaped responses are retained literally; no common reasoning or text shape is assumed.",
    "Human chat is excluded and counted because the users table is not exported. No human message is attributed to an agent; this also removes potential human-source context.",
    "Date slicing can remove earlier memory baselines; include a preceding snapshot before studying newly retained content.",
    "Joins for event rows are validated only within the selected date window. Excluded event rows are counted without becoming findings.",
    "These tables do not contain independent message read receipts or exact llm_calls prompts. No candidate transmission or causal-uptake edges are generated by this adapter.",
    "Source paths and row hashes identify local evidence; the dataset card URL is documentation, not a public row permalink.",
    "created_at is the database row creation time. updated_at is preserved; current text can reflect later changes, and historical row versions are unavailable.",
    "An update gap over one second is flagged for chronology review as a triage heuristic, not an authenticated edit detector. Smaller gaps do not verify historical content either.",
    "A row update gap over one second raises a content-time warning. This is an analysis threshold, not proof that shorter gaps imply immutable text.",
    "Output ordering uses created_at timestamps only. Ties are displayed deterministically, not claimed to follow canonical events.event_index ordering.",
    "The supplied schema says tables were exported sequentially from a live database. An unresolved selected-row join is reported as incomplete input rather than silently discarded.",
]


class AdapterError(ValueError):
    """A diagnostic includes its source table/line whenever a row is invalid."""


def _digest(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _canonical(value) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")


def _uuid(value, context: str) -> str:
    if not isinstance(value, str):
        raise AdapterError(context + ": expected a UUID string")
    try:
        result = UUID(value)
    except ValueError as exc:
        raise AdapterError(context + ": invalid UUID") from exc
    # UUID strings may differ in letter case; UUID objects give canonical joins.
    return str(result)


def parse_utc_timestamp(value: str, context: str = "timestamp") -> datetime:
    """Accept documented naive UTC timestamps and explicit ISO timezone forms."""
    if not isinstance(value, str) or not _STAMP.fullmatch(value):
        raise AdapterError(context + ": expected a timestamp with date and time")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise AdapterError(context + ": invalid timestamp") from exc
    return parsed.replace(tzinfo=timezone.utc) if parsed.tzinfo is None else parsed.astimezone(timezone.utc)


def _boundary(value: str | None, context: str) -> datetime | None:
    if value is None:
        return None
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        value += " 00:00:00"
    return parse_utc_timestamp(value, context)


def _text(row: dict, key: str, context: str, nullable: bool = False) -> str | None:
    if key not in row:
        raise AdapterError(context + ": missing " + key)
    value = row[key]
    if nullable and value is None:
        return None
    if not isinstance(value, str):
        raise AdapterError(context + ": " + key + " must be text" + (" or null" if nullable else ""))
    return value


def _local_file(path: str | Path, context: str) -> Path:
    if isinstance(path, str) and "://" in path:
        raise AdapterError(context + ": only local file paths are supported")
    target = Path(path)
    if not target.is_file():
        raise AdapterError(context + ": local file does not exist: " + str(target))
    return target


def _file_meta(path: Path, table: str) -> dict:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return {"table": table, "path": str(path), "sha256": digest.hexdigest(), "bytes": path.stat().st_size}


def _rows(path: Path, table: str) -> Iterator[tuple[dict, dict]]:
    """Stream rows; do not retain the full computer-use export in memory."""
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rb") as stream:
        for position, payload in enumerate(stream, 1):
            if not payload.strip():
                continue
            context = table + ":" + str(position)
            try:
                row = json.loads(payload)
            except (json.JSONDecodeError, UnicodeDecodeError) as exc:
                raise AdapterError(context + ": invalid JSON row") from exc
            if not isinstance(row, dict):
                raise AdapterError(context + ": expected a JSON object")
            try:
                row_hash = _digest(_canonical(row))
            except (TypeError, ValueError) as exc:
                raise AdapterError(context + ": unsupported JSON value") from exc
            yield row, {"table": table, "source_file": str(path), "row_position": position,
                "row_sha256": row_hash, "raw_line_sha256": _digest(payload), "context": context}


def _known_agent(value, agents: dict, context: str) -> str:
    identity = _uuid(value, context)
    if identity not in agents:
        raise AdapterError(context + ": unresolved agent UUID " + identity + "; supply its agents row")
    return identity


def import_ai_village(
    files: dict[str, str | Path], *, manifest_path: str | Path | None = None,
    dataset_revision: str | None = None, start: str | None = None, end: str | None = None,
    synthetic: bool = False, max_events: int = 50000,
) -> dict:
    """Import supported local table files into the RelayTrace event contract.

    ``files`` maps exact table names to JSONL or JSONL.GZ paths. Agents are
    required. Turns also require sessions. Start is inclusive and end exclusive
    in UTC; YYYY-MM-DD boundaries mean UTC midnight. Foreign keys are validated
    before any selected record is emitted. A rejected import produces no file.
    """
    unknown = set(files) - set(TABLES)
    if unknown:
        raise AdapterError("Unsupported table(s): " + ", ".join(sorted(unknown)))
    if "agents" not in files:
        raise AdapterError("agents is required for stable identity joins")
    if "computer_use_turns" in files and "computer_use_sessions" not in files:
        raise AdapterError("computer_use_turns requires computer_use_sessions for its session_id join")
    if max_events < 1:
        raise AdapterError("max_events must be positive")
    paths = {table: _local_file(path, table) for table, path in files.items()}
    metadata = {table: _file_meta(path, table) for table, path in paths.items()}
    since, until = _boundary(start, "start"), _boundary(end, "end")
    if since and until and until <= since:
        raise AdapterError("end must be later than start")

    def selected(stamp: datetime) -> bool:
        return (since is None or stamp >= since) and (until is None or stamp < until)

    manifest = None
    manifest_meta = None
    if manifest_path is not None:
        path = _local_file(manifest_path, "manifest")
        manifest_meta = _file_meta(path, "manifest")
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise AdapterError("manifest: invalid JSON") from exc
        if not isinstance(manifest, dict):
            raise AdapterError("manifest: expected a JSON object")
        _uuid(manifest.get("villageId"), "manifest.villageId")
        parse_utc_timestamp(manifest.get("exportedAt"), "manifest.exportedAt")

    agents, sessions = {}, {}
    counts = Counter()
    duplicates = Counter()
    source_ids = {}

    def identity(row: dict, provenance: dict) -> tuple[str, bool]:
        rid = _uuid(row.get("id"), provenance["context"] + ".id")
        table = provenance["table"]
        key = (table, rid)
        previous = source_ids.get(key)
        if previous and previous != provenance["row_sha256"]:
            raise AdapterError(provenance["context"] + ": conflicting duplicate row UUID " + rid)
        if previous:
            duplicates[table] += 1
            return rid, False
        source_ids[key] = provenance["row_sha256"]
        return rid, True

    village_ids = set()
    for row, proof in _rows(paths["agents"], "agents"):
        counts["agents"] += 1
        rid, is_new = identity(row, proof)
        if not is_new:
            continue
        village = _uuid(row.get("village_id"), proof["context"] + ".village_id")
        village_ids.add(village)
        agents[rid] = {"id": rid, "name": _text(row, "name", proof["context"]),
            "model_string": _text(row, "model_string", proof["context"]), "village_id": village,
            "metadata_scope": "export-state; not verified historical roster", "created_at": row.get("created_at"), "updated_at": row.get("updated_at"),
            "provenance": {**proof, "source_row_id": rid, "source_file_sha256": metadata["agents"]["sha256"]}}
    if not agents:
        raise AdapterError("agents: no agent metadata rows")
    if len(village_ids) != 1:
        raise AdapterError("agents: ambiguous mixed-village input")
    village_id = next(iter(village_ids))
    if manifest and _uuid(manifest["villageId"], "manifest.villageId") != village_id:
        raise AdapterError("manifest villageId does not match agents.village_id")

    events = []
    outside_window = Counter()
    excluded_humans = 0

    def emit(row: dict, proof: dict, row_id: str, agent_id: str, stamp: datetime,
             event_type: str, text: str, *, payload=None, session_id=None, room_id=None) -> None:
        if len(events) >= max_events:
            raise AdapterError("Selected event limit exceeded; narrow --start/--end or increase --max-events")
        agent = agents[agent_id]
        event_id = "aiv_" + _digest(_canonical([proof["table"], row_id, event_type]))[:24]
        updated = parse_utc_timestamp(row["updated_at"], proof["context"] + ".updated_at") if row.get("updated_at") is not None else None
        materially_updated = updated is not None and abs((updated - stamp).total_seconds()) > MATERIAL_UPDATE_WARNING_SECONDS
        events.append({
            "id": event_id, "timestamp": stamp.isoformat().replace("+00:00", "Z"),
            "timestamp_raw": row["created_at"], "timestamp_grade": "database-created-at",
            "timestamp_uncertainty_seconds": None,
            "actor_id": agent_id, "actor_handle": agent["name"], "actor_kind": "agent",
            "model_string": agent["model_string"], "village_id": village_id,
            "model_metadata_scope": "export-state; historical model version unverified",
            "content_time_status": "unresolved-current-row-updated" if materially_updated else "row-created-at; historical text version not independently verified",
            "materially_later_update": bool(updated and (updated - stamp).total_seconds() > MATERIAL_UPDATE_WARNING_SECONDS),
            "page": proof["table"] + (":" + session_id if session_id else ""),
            "page_key": proof["table"] + (":" + session_id if session_id else ""),
            "session_id": session_id, "room_id": room_id,
            "event_type": event_type, "text": text, "payload": payload,
            "source_url": None, "source_revision_id": row_id,
            "content_sha256": _digest(_canonical(payload if payload is not None else text)),
            "receipt_observed": False, "causal_uptake_observed": False,
            "action_success_verified": False,
            "provenance": {**{key: value for key, value in proof.items() if key != "context"},
                "source_row_id": row_id, "record_path": proof["source_file"] + ":" + str(proof["row_position"]),
                "source_file_sha256": metadata[proof["table"]]["sha256"],
                "created_at": row["created_at"], "updated_at": row.get("updated_at"),
                "updated_at_utc": updated.isoformat().replace("+00:00", "Z") if updated else None,
                "content_time_warning": "Current content may reflect a later mutation; do not assume it existed at created_at." if materially_updated else None,
                "schema_basis": "user-supplied AI Village column reference",
                "timestamp_contract": "created_at; documented naive strings are UTC"},
        })

    if "computer_use_sessions" in paths:
        for row, proof in _rows(paths["computer_use_sessions"], "computer_use_sessions"):
            counts["computer_use_sessions"] += 1
            rid, is_new = identity(row, proof)
            if not is_new:
                continue
            agent_id = _known_agent(row.get("agent_id"), agents, proof["context"] + ".agent_id")
            village = _uuid(row.get("village_id"), proof["context"] + ".village_id")
            if village != agents[agent_id]["village_id"]:
                raise AdapterError(proof["context"] + ": session village_id conflicts with its agent")
            goal = _text(row, "session_goal", proof["context"])
            stamp = parse_utc_timestamp(row.get("created_at"), proof["context"] + ".created_at")
            sessions[rid] = {"id": rid, "agent_id": agent_id, "created_at": stamp,
                "provenance": {**proof, "source_row_id": rid, "source_file_sha256": metadata["computer_use_sessions"]["sha256"]}}
            if selected(stamp):
                emit(row, proof, rid, agent_id, stamp, "session_intention", goal, session_id=rid)
            else:
                outside_window["computer_use_sessions"] += 1

    for table in ("chat_messages", "agent_memories", "computer_use_turns"):
        if table not in paths:
            continue
        for row, proof in _rows(paths[table], table):
            counts[table] += 1
            stamp = parse_utc_timestamp(row.get("created_at"), proof["context"] + ".created_at")
            if not selected(stamp):
                outside_window[table] += 1
                continue
            rid, is_new = identity(row, proof)
            if not is_new:
                continue
            if table == "chat_messages":
                kind = row.get("speaker_type")
                if kind == "user":
                    if row.get("agent_speaker_id") is not None:
                        raise AdapterError(proof["context"] + ": human message has ambiguous agent_speaker_id")
                    excluded_humans += 1
                    continue
                if kind != "agent":
                    raise AdapterError(proof["context"] + ": unknown speaker_type")
                if row.get("user_speaker_id") is not None:
                    raise AdapterError(proof["context"] + ": agent message also has user_speaker_id")
                agent_id = _known_agent(row.get("agent_speaker_id"), agents, proof["context"] + ".agent_speaker_id")
                room = _uuid(row.get("room_id"), proof["context"] + ".room_id")
                emit(row, proof, rid, agent_id, stamp, "chat_message", _text(row, "content", proof["context"]), room_id=room)
            elif table == "agent_memories":
                agent_id = _known_agent(row.get("agent_id"), agents, proof["context"] + ".agent_id")
                emit(row, proof, rid, agent_id, stamp, "memory_snapshot", _text(row, "content", proof["context"]))
            else:
                sid = _uuid(row.get("session_id"), proof["context"] + ".session_id")
                if sid not in sessions:
                    raise AdapterError(proof["context"] + ": unresolved session UUID " + sid + "; supply its computer_use_sessions row")
                agent_id = sessions[sid]["agent_id"]
                if "agent_action" not in row or (row["agent_action"] is not None and not isinstance(row["agent_action"], dict)):
                    raise AdapterError(proof["context"] + ": agent_action must be an object or null")
                response = row.get("agent_messages")
                if not isinstance(response, (dict, list)):
                    raise AdapterError(proof["context"] + ": agent_messages must retain its provider-shaped object/array")
                if row["agent_action"] is not None:
                    emit(row, proof, rid, agent_id, stamp, "executed_action", json.dumps(row["agent_action"], ensure_ascii=False, sort_keys=True), payload=row["agent_action"], session_id=sid)
                emit(row, proof, rid, agent_id, stamp, "model_response", "Provider-shaped model response; narration is not classified as execution.", payload=response, session_id=sid)
                result = {key: _text(row, key, proof["context"], nullable=True) for key in ("output", "error", "system")}
                if any(value is not None for value in result.values()):
                    emit(row, proof, rid, agent_id, stamp, "tool_output", "\n".join(key + ": " + value for key, value in result.items() if value is not None), payload=result, session_id=sid)
                for event in events[-3:]:
                    if event["source_revision_id"] == rid and event["provenance"]["table"] == table:
                        event["provenance"]["session_identity_link"] = {"session_id": sid, "agent_id": agent_id,
                            "session_row_sha256": sessions[sid]["provenance"]["row_sha256"],
                            "session_source_file": sessions[sid]["provenance"]["source_file"],
                            "session_row_position": sessions[sid]["provenance"]["row_position"]}
                        event["screenshot_is_redacted"] = row.get("screenshot_is_redacted")
                        event["has_redaction_been_overruled"] = row.get("has_redaction_been_overruled")

    events.sort(key=lambda event: (parse_utc_timestamp(event["timestamp"]), event["provenance"]["table"], event["source_revision_id"], event["event_type"]))
    event_counts = Counter(event["event_type"] for event in events)
    fingerprint = _digest(_canonical({table: record["sha256"] for table, record in sorted(metadata.items())}))
    return {
        "schema_version": "1.0",
        "dataset": {"id": "ai-village-local-" + fingerprint[:16],
            "title": "SYNTHETIC AI Village adapter fixtures" if synthetic else "Local AI Village table import",
            "source_url": SOURCE_CARD, "synthetic": synthetic,
            "access_class": "synthetic-fixtures" if synthetic else "restricted-research",
            "acquisition_mode": "synthetic-local-fixtures" if synthetic else "local-files; source authenticity unverified",
            "source_files": list(metadata.values()), "sha256": fingerprint,
            "dataset_revision": dataset_revision or "unknown", "official_revision_authenticated": False,
            "schema_basis": "user-supplied column reference; not official-version validation",
            "village_id": village_id, "exported_at": manifest.get("exportedAt") if manifest else None,
            "manifest_provenance": manifest_meta, "manifest_supplied": manifest is not None,
            "manifest_row_counts": manifest.get("rowCounts") if manifest else None,
            "manifest_dropped_columns": manifest.get("droppedColumns") if manifest else None,
            "coverage_note": "Manifest rowCounts describe the supplied full export; local files can be partial and are counted separately.",
            "source_metadata_status": "user-supplied manifest" if manifest else "export metadata unknown",
            "date_window_utc": {"basis": "row.created_at; current-content historical time may be unresolved", "start_inclusive": since.isoformat() if since else None, "end_exclusive": until.isoformat() if until else None},
            "ordering_basis": "created_at UTC; deterministic tie display is not canonical events.event_index order",
            "material_update_warning_threshold_seconds": MATERIAL_UPDATE_WARNING_SECONDS,
            "limitations": LIMITATIONS},
        "summary": {"event_count": len(events), "edge_count": 0, "actors": len({event["actor_id"] for event in events}),
            "pages": len({event["page"] for event in events}), "input_rows_by_table": dict(counts),
            "duplicate_rows_by_table": dict(duplicates), "outside_window_rows_by_table": dict(outside_window),
            "excluded_human_chat_rows": excluded_humans, "unresolved_selected_joins": 0,
            "event_counts_by_type": dict(event_counts), "observed_receipts": 0, "verified_causal_uptake": 0},
        "agent_metadata": list(agents.values()), "events": events, "edges": [], "episodes": [],
    }


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=Path("data/raw/ai-village"))
    parser.add_argument("--out", type=Path, default=Path("data/processed/ai-village-evidence.json"))
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--dataset-revision")
    parser.add_argument("--start", help="Inclusive UTC timestamp or date")
    parser.add_argument("--end", help="Exclusive UTC timestamp or date")
    parser.add_argument("--max-events", type=int, default=50000)
    parser.add_argument("--synthetic", action="store_true", help="Explicitly label synthetic test inputs; never real findings")
    args = parser.parse_args(argv)
    files = {}
    for table in TABLES:
        candidates = [path for path in (args.input_dir / (table + ".jsonl.gz"), args.input_dir / (table + ".jsonl")) if path.is_file()]
        if len(candidates) > 1:
            parser.error("Ambiguous input: both JSONL and gzipped JSONL exist for " + table)
        if candidates:
            files[table] = candidates[0]
    manifest = args.manifest or (args.input_dir / "manifest.json" if (args.input_dir / "manifest.json").is_file() else None)
    try:
        evidence = import_ai_village(files, manifest_path=manifest, dataset_revision=args.dataset_revision,
            start=args.start, end=args.end, synthetic=args.synthetic, max_events=args.max_events)
    except (AdapterError, OSError) as exc:
        parser.exit(2, "AI Village import rejected: " + str(exc) + "\n")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.out.with_suffix(args.out.suffix + ".tmp")
    try:
        temporary.write_text(json.dumps(evidence, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
        temporary.replace(args.out)
    finally:
        temporary.unlink(missing_ok=True)
    print(json.dumps(evidence["summary"], indent=2))


if __name__ == "__main__":
    main()
